config/routes.rb
Rails.application.routes.draw do

  get "/hello/" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get  "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  resources :questions do
    get   :search,    on: :collection
    patch :mark_done, on: :member
    post  :approve

    resources :answers, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  # This will establish a `has_many` association with answers. This assumes
  # that your answer model has a `question_id` integer field that references
  # the question. with has_many `answers` must be plural (Rails convention).
  # We must pass a `dependent` option to maintain data integrity. The possible
  # values you can give it are: :destroy or :nullify
  # With :destroy: if you delete a question it will delete all associated answers
  # With :nullify: if you delete a question it will update the `question_id` NULL
  #                for all associated records (they won't get deleted)
  has_many :answers, dependent: :destroy

  # This enables us to access all the comments created for all the question's
  # answers. This generates a single SQL statement with `INNER JOIN` to
  # accompolish it
  has_many :comments, through: :answers

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  has_many :favourites, dependent: :destroy
  has_many :favrouting_users, through: :favourites, source: :user


  # this will fail validations (so it won't create or save) if the title is
  # not provided
  validates :title, presence:   true,
                    uniqueness: { case_sensitive: false },
                    length:     {minimum: 3, maximum: 255}

  # DSL: Domain Specific Language
  # the code we use in here is completely valid Ruby code but the method naming
  # and arguments are specific to ActiveRecord so we call this an ActiveRecord
  # DSL
  validates(:body, {uniqueness: {message: "must be unique!"}})

  # this validates that the combination of the title and body is unique. Which
  # means the title doesn't have to be unique by itself and the body doesn't
  # have to be unique by itself. However, the combination of the two fields
  # must be unique
  # validates :title, uniqueness: {scope: :body}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  #   validates :email,
  #             format: { with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

  # This is using custom validation method. We must make sure that `no_monkey`
  # is a method available for our class. The method can be public or private
  # It's more likely we will have it a private method because we don't need
  # to use it outside this class.
  validate :no_monkey

  after_initialize :set_defaults
  before_save :capitalize_title

  # scope :recent, lambda {|x| order("created_at DESC").limit(x) }
  def self.recent(number = 5)
    order("created_at DESC").limit(number)
  end

  def self.popular
    where("view_count > 10")
  end

  # Wildcard search by title or body
  # ordered by view_count in a descending order
  def self.search(term)
    where(["title ILIKE ? OR body ILIKE ?", "%#{term}%", "%#{term}%"]).
    order("view_count DESC")
  end

  def category_name
    category.name if category
  end

  # delegate :full_name, to: :user, prefix: true, allow_nil: true
  def user_full_name
    user.full_name if user
  end

  def like_for(user)
    likes.find_by_user_id user
  end

  def fav_for(user)
    favourites.find_by_user_id user
  end

  private

  def set_defaults
    self.view_count ||= 0
  end

  def capitalize_title
    self.title.capitalize!
  end

  def no_monkey
    if title && title.downcase.include?("monkey")
      errors.add(:title, "No monkey!!")
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # this `before_action` will call the `find_question` method before executing
  # any other action.
  # we can specify :only or :except to be more speicfic about the actions
  # which the before_action apply to
  # before_action :find_question, except: [:new, :create, :index]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user, except: [:index, :show]

  before_action :authorize_user, only: [:edit, :update, :destroy]

  def new
    @question = Question.new
  end

  def create
    # params => {"question"=>{"title"=>"hello world", "body"=>"something here"}}
    # question       = Question.new
    # question.title = params[:question][:title]
    # question.body  = params[:question][:body]

    @question      = Question.new question_params
    @question.user = current_user
    if @question.save
      # all these formats are possible ways to redirect in Rails:
      # redirect_to question_path({id: @question.id})
      # redirect_to question_path({id: @question})
      # redirect_to @question
      flash[:notice] = "Question Created Successfully!"
      redirect_to question_path(@question)
    else
      # This will render app/views/questions/new.html.erb template
      # we need to be explicit about rendering the new template becuase the
      # default behaviour is to render `create.html.erb`
      # you can specify full path such as: render "/questions/new"
      flash[:alert] = "Question wasn't created. Check errors below"
      render :new
    end
  end

  # GET: /questions/13
  def show
    @question.view_count += 1
    @question.save
    @answer = Answer.new
  end

  def index
    @questions = Question.all
  end

  def edit
  end

  def update
    # We call the update with sanitized params
    if @question.update question_params
      # we redirect to the question show page
      redirect_to(question_path(@question), {notice: "Question updated!"})
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    # we redirect to the index page
    redirect_to questions_path, notice: "Question deleted!"
  end

  private

  def question_params
    # using params. require ensures that there is a key called `question` in my
    # params. the `permit` method will only allow paramsters that you explicitly
    # list, in this case: title and body
    # this is called Strong Paramters
    params.require(:question).permit([:title, :body, :category_id])
  end

  def find_question
    @question = Question.find params[:id]
  end

  def authorize_user
    unless can? :manage, @question
      redirect_to root_path, alert: "access denied!"
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= @question.errors.full_messages.join(", ") %>
<%# form_for takes in an ActiveRecord object as a first arguemnt. Then it looks
    at the object. If the object is not persisted (not yet saved to the database)
    The form will automatically use POST for its `method`. It will also automatically
    use `questions_path` as its action (convention is that the `questions_path`
    will submit to the `create` action)%>
<%# if @question is persisted then the form will send PATCH request by adding
    a hidden field with name _method and value `patch`. The action url will be
    question_path(@question) (by convention). The form will prepopulate the
    fields with existing values for `@question` %>
<%= form_for @question do |f| %>
  <%# we call `f` the form object %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div>
    <%= f.label :category_id %>
    <%= f.collection_select(:category_id, Category.order(:name), :id, :name, {}, {class:"form-control"}) %>
  </div>
  <div>
    <%= f.submit nil, class:"btn btn-default" %>
  </div>

<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <h1>Edit Question</h1>

<%= render "form" %>
</div>

app/views/questions/index.html.erb
<div class="jumbotron text-center bg-grey">
  <h1>All Questions (<%= @questions.length %>)</h1>
  <!-- <p><%= image_tag "red-panda.jpg", class:"panda" %></p> -->
</div>


<!-- <img src="/images/red-panda.jpg"> -->
<div class="container">
  <table class="table table-striped">
<% @questions.each do |question| %>
    <tr>
      <td>
        <%= link_to question.title, question_path(question) %>
      </td>
    </tr>
<% end %>
  </table>
</div>

app/views/questions/new.html.erb
<div class="container">
<h1>New Question</h1>

<%# this will look for a partial named "_form" within the same folder as
    this template (new.html.erb). The partial will have access to the instance
    varibles that this template has access to. You pass local variables by
    passing a Hash to the partial as in:
    = render "form", my_var: my_variable
    so inside the _form partial you will have a local varible defined called
    `my_var`
    %>
<%= render "form" %>
</div>

app/views/questions/show.html.erb
<!-- question -->
<div class="container">
  <h1><%= @question.title %></h1>
  <div class="col-sm-9 col-xs-12">
    <p><%= @question.body %></p>
    <% like = @question.like_for(current_user) %>
    <% if like %>
      <%= link_to fa_icon("thumbs-up"), question_like_path(@question, like), method: :delete, class: "like-fav-icon"  %>
    <% else %>
      <%= link_to fa_icon("thumbs-o-up"), question_likes_path(@question), method: :post, class: "like-fav-icon" %>
    <% end %>
    <span class="badge"><%= @question.likes.count %></span>

    <% fav = @question.fav_for(current_user) %>
    <% if fav %>
      <%= link_to fa_icon("heart"), question_favourite_path(@question, fav), method: :delete, class: "like-fav-icon" %>
    <% else %>
      <%= link_to fa_icon("heart-o"), question_favourites_path(@question), method: :post, class: "like-fav-icon" %>
    <% end %>
    <span class="badge"><%= @question.favourites.count %></span>
    <br><br>
    <div class="btn-group">
    <% if can? :edit, @question %>
      <%= link_to "Edit", edit_question_path(@question), class:"btn btn-default btn-sm" %>
    <% end %>

    <% if can? :destroy, @question %>
      <%#  method: :delete asks Rails to send a DELETE request instead of GET which
          is accomplished using Javascript/jQuery %>
      <%= link_to "Delete",
                  question_path(@question),
                  method: :delete,
                  data: {confirm: "Are you sure?"},
                  class:"btn btn-default btn-sm" %>
    <% end %>

    </div>
    <hr>
  </div>

<!-- info box -->
  <div class="col-md-3 col-sm-6 col-xs-12">
    <ul class="list-group">
      <li class="list-group-item">View Count:
        <span class="badge"><%= @question.view_count %></span>
      </li>
      <li class="list-group-item"><%= @question.created_at %></li>
      <li class="list-group-item">Category: <%= @question.category_name %></li>
      <li class="list-group-item">Created By: <%= @question.user_full_name %></li>
    </ul>
  </div>

<!-- answer -->
  <div class="container">
    <%# This is the like object for the `current_user` and `@question` %>
    <h2>Answers</h2>
    <p>Create an Answer</p>
<%# we can use the form after overriding the `url` parameter. The downside to it
    is that it won't work for `edit` situation. This will only work in `create`
    situation. So we can't reuse it we decide to implement editing answers.%>
<%#= form_for @answer, url: question_answers_path(@question) do |f| %>
<%# end %>

    <%= @answer.errors.full_messages.join(", ") %>
<%# passing an array to the `form_for` is a better approach for creating nested
    resources. This approach will work for both new / edit sitatuions. So if
    @answer is not persisted it will send a POST request to
    question_answers_path(@question). And if @answer is persisted it will send
    a PATCH request to question_answer_path(@question, @answer) %>
    <%= form_for [@question, @answer] do |f| %>
    <div>
      <%= f.text_area :body, class:"form-control" %>
    </div>
  <%= f.submit nil, class:"btn btn-default" %>
<% end %>

    <br><br>
    <table class="table table-striped">
<% @question.answers.each do |ans| %>
    <tr>
      <td>
  <%= ans.body %> (by: <%= ans.user_full_name %>)
  <% if can? :destroy, ans %>
    <%= link_to "Delete", question_answer_path(@question, ans),
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                        class: "btn btn-default btn-xs" %>
  <% end %>
      </td>
    </tr>
<% end %>
  </div>
</div>