config/routes.rb
Rails.application.routes.draw do

  get "/hello/" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get  "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  resources :questions do
    get   :search,    on: :collection
    patch :mark_done, on: :member
    post  :approve

    resources :answers, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "questions#index"

end

app/views/layouts/application.html.erb
<%# this will be used as a default layout. %>
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- navigation   -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-left" href="#"><%= image_tag "logo" %></a>
      <a class="navbar-brand navbar-left" href="#">Awesome Answers</a>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right data-toggle="collapse" data-target=".navbar-collapse.in">
          <li><a href="<%= about_path %>">About</a></li>
          <li><a href="<%= greet_path('John') %>"> Greet John </a></li>
          <li><%= link_to "Hello", hello_path %></li>
          <li><%= link_to "Subscribe", subscribe_path %></li>
          <li><%= link_to "New Question", new_question_path %></li>
          <li><%= link_to "All Questions", questions_path %></li>

          <% if session[:user_id] %>
            <li><%= link_to "Favourites", favourites_path %></li>
            <li><a href="#">Hello <%= current_user.first_name %></a></li>
            <li><%= link_to "Log out", sessions_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<!-- <a href="/hello">Hello</a> |
<a href="/about">About</a> | -->
<%# hello_path & about_path are called route helpers. They get generated from
    the content of `routes.rb` and they are methods that can be used in
    all view files and all controllers %>

<!-- <a href="<%= about_path %>">About</a> | -->
<!-- <a href="<%= greet_path({name: 'John'}) %>"> Greet John </a> -->
<!-- <a href="<%= greet_path('John') %>"> Greet John </a> | -->

<%# link_to is a helper method that is built-in with Rails, it's a view helper
    method, meaning it's accessible only in the views / view helpers. link_to
    takes a first argument which is the anchor text and a second argument which
    is the `href` value (url/path). It can take other options as we will see
    later. More info here:
    http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to %>
<!-- <%= link_to "Hello", hello_path %> |
<%= link_to "Subscribe", subscribe_path %> |
<%= link_to "New Question", new_question_path %> |
<%= link_to "All Questions", questions_path %> |

<% if user_signed_in? %>
  <%= link_to "Favourites", favourites_path %> |
  Hello <%= current_user.first_name %>
  <%= link_to "Log out", sessions_path, method: :delete %>
<% else %>
  <%= link_to "Sign Up", new_user_path %>
<% end %> -->

<%#= flash[:notice] || flash[:alert] %>

<!-- notice and alerts -->
<% if notice %>
  <div class="alert alert-success alert-dismissible">
    <strong><%= notice %></strong>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible">
    <strong><%= alert %></strong>
  </div>
<% end %>
<%#= notice || alert %>

<%= yield %>

</body>
</html>